### ISSUE TITLE
R Climate Data Graph

### ISSUE THREAD

**Issue by DaveJarvis** [PranavAmarnath/RisingTemperatures#2]
FYI, check out graph.R and the build/fetch scripts:

https://gitlab.com/DaveJarvis/impacts/-/tree/master/climate

**Comment by PranavAmarnath** [comment]
@DaveJarvis Thank you for the link! I hope to incorporate a fetch script or perhaps directly a URL to load the CSV data instead of packaging the files within the JAR. By the way, your generated graph.svg visualizes the data quite well :-).

**Comment by DaveJarvis** [comment]
> @DaveJarvis Thank you for the link! I hope to incorporate a fetch script or perhaps directly a URL to load the CSV data instead of packaging the files within the JAR. 

By using R, the fetch script is a little bit superfluous because R could grab the data directly. Of course, a Java URL connection would work well in your case.

> graph.svg visualizes the data quite well :-).

Thanks! It's from part of my book: https://impacts.to/downloads/lowres/impacts.pdf
